kind: pipeline
name: Build .NET
type: docker

steps:
  - name: .NET Build
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
    - dotnet restore src/Notary.sln --no-cache --use-current-runtime -v q --nologo 
    - dotnet build src/Notary.sln -c Release --no-restore -v q -o dist/ --nologo
    - dotnet test ./src/test/ --nologo -v q