on:
  push:
    branches: [main]

jobs:
  build-api:
    name: Docker Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Build Action v2
        uses: docker/setup-buildx-action@v2
      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/notary-api:latest
            ${{ secrets.DOCKER_HUB_USER }}/notary-api:${{ vars.NOTARY_MAJOR_VERSION }}.${{ vars.NOTARY_MINOR_VERSION }}.${{ github.run_number }}
  build-web:
    name: Docker Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Build Action v2
        uses: docker/setup-buildx-action@v2
      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/web/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/notary-web:latest
            ${{ secrets.DOCKER_HUB_USER }}/notary-web:${{ vars.NOTARY_MAJOR_VERSION }}.${{ vars.NOTARY_MINOR_VERSION }}.${{ github.run_number }}
  tag:
    needs: [build-api, build-web]
    name: Create Tag in GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        uses: actions/github-script@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ vars.NOTARY_MAJOR_VERSION }}.${{ vars.NOTARY_MINOR_VERSION }}.${{ github.run_number }}',
              sha: context.sha
            })
